name: 'Odoo Test & Code Climate'
description: 'Ejecuta tests de Odoo y reporta a Code Climate'
author: 'Chroma Agency'

inputs:
  odoo_version:
    description: 'Versi칩n de Odoo'
    required: true
    default: '16.0'
  modules:
    description: 'M칩dulos a probar'
    required: true
  pg_version:
    description: 'Versi칩n de Postgres'
    required: false
    default: '14'
  test_tags:
    description: 'Tags de test opcionales'
    required: false
    default: ''
  # NUEVOS INPUTS PARA ENTERPRISE
  enterprise_deploy_key:
    description: 'GitHub Token con acceso a odoo/enterprise'
    required: false
    default: ''
  # INPUT PARA CODE CLIMATE
  qlty_coverage_token:
    description: 'Token de Code Climate para reportar coverage'
    required: false
    default: ''

runs:
  using: "composite"
  steps:

    # 1. Infraestructura (Red + DB)
    - name: Crear red Docker
      shell: bash
      run: docker network create odoo-test-network || true
    # 1. Cargamos la llave SSH en el agente
    - name: Setup SSH Agent
      if: ${{ inputs.enterprise_deploy_key != '' }}
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ inputs.enterprise_deploy_key }}
    # NUEVO: Clonar Odoo Enterprise
    - name: Clonar Odoo Enterprise
      if: ${{ inputs.enterprise_deploy_key != '' }}
      shell: bash
      run: |
        git clone --depth 1 --branch ${{ inputs.odoo_version }} \
          git@github.com:ChromaAgency/odoo-enterprise.git \
          ${{ github.workspace }}/enterprise

    - name: Iniciar Postgres
      shell: bash
      run: |
        docker rm -f db-postgres || true
        docker run -d --name db-postgres --network odoo-test-network \
          -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo -e POSTGRES_DB=postgres \
          postgres:${{ inputs.pg_version }}

    - name: Esperar a Postgres
      shell: bash
      run: until docker exec db-postgres pg_isready -U odoo; do sleep 2; done

    - name: Ajustar permisos
      shell: bash
      run: chmod -R 777 .

    # 2. Ejecutar Tests (Generando coverage.xml)
    - name: Ejecutar Tests Odoo
      uses: addnab/docker-run-action@v3
      with:
        image: odoo:${{ inputs.odoo_version }}
        options: >-
          --user root
          -v ${{ github.workspace }}:/mnt/extra-addons
          -v ${{ github.workspace }}/enterprise:/mnt/enterprise
          --network odoo-test-network
          -e HOST=db-postgres
          -e USER=odoo
          -e PASSWORD=odoo
          -e INPUT_MODULES=${{ inputs.modules }}
          -e INPUT_TAGS=${{ inputs.test_tags }}
          -e INPUT_QLTY_COVERAGE_TOKEN=${{ inputs.qlty_coverage_token }}
        run: |
          set -e  # Exit immediately if any command fails
          
          # Instalar coverage
          if [ -n "$INPUT_QLTY_COVERAGE_TOKEN" ]; then pip install coverage --break-system-packages; fi

          # Preparar Tags
          TAGS_FLAG=""
          if [ -n "$INPUT_TAGS" ]; then TAGS_FLAG="--test-tags=$INPUT_TAGS"; fi

          # Definir addons path (incluye enterprise si existe)
          ADDONS_PATH="/mnt/extra-addons"
          if [ -d "/mnt/enterprise" ]; then ADDONS_PATH="$ADDONS_PATH,/mnt/enterprise"; fi

          # Definir comando base con par치metros de DB
          CMD="odoo -i $INPUT_MODULES --test-enable $TAGS_FLAG --stop-after-init --database=test_db --log-level=test --db_host=db-postgres --db_port=5432 --db_user=odoo --db_password=odoo --addons-path=$ADDONS_PATH"

          # Si hay ID de Code Climate, envolvemos con coverage
          if [ -n "$INPUT_QLTY_COVERAGE_TOKEN" ]; then
            echo "游빍 Corriendo con Coverage..."
            python3 -m coverage run --source=/mnt/extra-addons --omit=*/__manifest__.py,*/tests/* /usr/bin/odoo -i $INPUT_MODULES --test-enable $TAGS_FLAG --stop-after-init --database=test_db --log-level=test --db_host=db-postgres --db_port=5432 --db_user=odoo --db_password=odoo --addons-path=$ADDONS_PATH
            
            python3 -m coverage xml -o /mnt/extra-addons/coverage.xml
          else
            echo "游 Corriendo sin Coverage..."
            $CMD
          fi
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ${{ github.workspace }}/coverage.xml
        retention-days: 30

    # 4. Subir a Code Climate (Desde el Host)
    - name: Upload to Code Climate
      if: ${{ inputs.qlty_coverage_token != '' }}
      uses: qltysh/qlty-action/coverage@v2
      with:
        token: ${{ inputs.qlty_coverage_token }}
        files: ${{ github.workspace }}/coverage.xml
